version: '3.8'

services:
  # Djangoアプリケーション
  web:
    build: .
    container_name: persk_web
    restart: unless-stopped
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - persk_network

  # Nginxリバースプロキシ
  nginx:
    image: nginx:alpine
    container_name: persk_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - persk_network

  # PostgreSQLデータベース
  db:
    image: postgres:15-alpine
    container_name: persk_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-persk}
      - POSTGRES_USER=${POSTGRES_USER:-persk_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - persk_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  persk_network:
    driver: bridge
