# Generated by Django 5.2.5 on 2025-08-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="focuslog",
            name="subtask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.subtask",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subtask",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "todo"),
                    ("doing", "doing"),
                    ("paused", "paused"),
                    ("done", "done"),
                ],
                default="todo",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="focuslog",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "todo"),
                    ("doing", "doing"),
                    ("paused", "paused"),
                    ("done", "done"),
                ],
                default="todo",
                max_length=10,
            ),
        ),
    ]
