# Generated by Django 5.2.5 on 2025-08-29 00:46

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
from datetime import timedelta


def add_default_values(apps, schema_editor):
    """既存データにデフォルト値を設定"""
    Task = apps.get_model('tasks', 'Task')
    SubTask = apps.get_model('tasks', 'SubTask')
    UserProfile = apps.get_model('tasks', 'UserProfile')
    
    # 既存のTaskにデフォルト値を設定
    for task in Task.objects.all():
        if task.deadline is None:
            task.deadline = timezone.now() + timedelta(days=7)  # 1週間後
        if task.estimate_min is None or task.estimate_min < 5:
            task.estimate_min = 15  # 15分
        if task.importance is None:
            task.importance = 1  # 中程度
        task.save()
    
    # 既存のSubTaskにデフォルト値を設定
    for subtask in SubTask.objects.all():
        if subtask.estimate_min is None or subtask.estimate_min < 5:
            subtask.estimate_min = 15
        subtask.save()


def reverse_default_values(apps, schema_editor):
    """ロールバック用（何もしない）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_focuslog_subtask_subtask_completed_at_and_more'),
    ]

    operations = [
        # 1. まず既存データにデフォルト値を設定
        migrations.RunPython(add_default_values, reverse_default_values),
        
        # 2. UserProfileに新しいフィールドを追加
        migrations.AddField(
            model_name='userprofile',
            name='auto_sort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='archive_after_days',
            field=models.IntegerField(default=30),
        ),
        
        # 3. SubTaskに新しいフィールドを追加
        migrations.AddField(
            model_name='subtask',
            name='estimate_min',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='subtask',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        
        # 4. Taskフィールドを必須化
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimate_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(),
        ),
        
        # 5. SortLogモデルを新規作成
        migrations.CreateModel(
            name='SortLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('mode', models.CharField(max_length=8)),
                ('sorted_at', models.DateTimeField()),
                ('item_count', models.IntegerField()),
                ('top_ids', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['-sorted_at'],
            },
        ),
    ]
