# Generated by Django 5.2.3 on 2025-08-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_subtask_options_timelineevent_timelinelike"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="shared",
            field=models.BooleanField(default=False),
        ),
    ]
